import { colors } from './colors'
import { radius } from './radius'
import { shadows } from './shadows'
import { spacing } from './spacing'
import { typography } from './typography'

export const tokenCssVariables = {
  '--color-brand-primary': colors.brand.primary,
  '--color-brand-secondary': colors.brand.secondary,
  '--color-brand-accent': colors.brand.accent,
  '--color-neutral-light': colors.neutral.light,
  '--color-neutral-gray': colors.neutral.gray,
  '--color-neutral-dark': colors.neutral.dark,
  '--color-neutral-black': colors.neutral.black,
  '--color-neutral-white': colors.neutral.white,
  '--color-background-default': colors.background.default,
  '--color-background-dark': colors.background.dark,
  '--color-text-primary': colors.text.primary,
  '--color-text-secondary': colors.text.secondary,
  '--color-text-inverse': colors.text.inverse,
  '--color-success': colors.semantic.success,
  '--color-warning': colors.semantic.warning,
  '--color-error': colors.semantic.error,
  '--color-info': colors.semantic.info,
  '--font-family-primary': typography.fontFamily.primary,
  '--font-size-xs': typography.fontSize.xs,
  '--font-size-sm': typography.fontSize.sm,
  '--font-size-md': typography.fontSize.md,
  '--font-size-lg': typography.fontSize.lg,
  '--font-size-xl': typography.fontSize.xl,
  '--font-size-display': typography.fontSize.display,
  '--font-weight-regular': `${typography.fontWeight.regular}`,
  '--font-weight-medium': `${typography.fontWeight.medium}`,
  '--font-weight-semibold': `${typography.fontWeight.semibold}`,
  '--font-weight-bold': `${typography.fontWeight.bold}`,
  '--font-weight-extrabold': `${typography.fontWeight.extrabold}`,
  '--line-height-tight': `${typography.lineHeight.tight}`,
  '--line-height-normal': `${typography.lineHeight.normal}`,
  '--line-height-relaxed': `${typography.lineHeight.relaxed}`,
  '--space-0': spacing[0],
  '--space-1': spacing[1],
  '--space-2': spacing[2],
  '--space-3': spacing[3],
  '--space-4': spacing[4],
  '--space-5': spacing[5],
  '--space-6': spacing[6],
  '--space-8': spacing[8],
  '--space-10': spacing[10],
  '--space-12': spacing[12],
  '--space-16': spacing[16],
  '--space-20': spacing[20],
  '--radius-sm': radius.sm,
  '--radius-md': radius.md,
  '--radius-lg': radius.lg,
  '--radius-pill': radius.pill,
  '--shadow-sm': shadows.sm,
  '--shadow-md': shadows.md,
  '--shadow-lg': shadows.lg,
} as const
